### ISSUE TITLE
bash run.bashができない

### ISSUE THREAD

**Issue by shmpwk** [knorth55/73b2_kitchen_edgetpu_object_detection#1]
READMEの[download-and-prepare-73b2-kitchen-dataset](https://github.com/knorth55/73b2_kitchen_edgetpu_object_detection#download-and-prepare-73b2-kitchen-dataset)を実行しようとしていました．

dlbox上では，権限がなくて以下を実行することはできないのでしょうか．
```
$ bash run.bash
docker: Error response from daemon: privileged mode is incompatible with user namespaces.  You must run the container in the host namespace when running privileged mode.
See 'docker run --help'.
```
もし，これを実行するならば，ローカルにdockerの環境を整えることになるのでしょうか．

**Comment by knorth55** [comment]
ここではなくて
https://github.com/knorth55/coral_usb_ros/tree/master/training/labelme_voc
こっちを参考にしてください。

**Comment by shmpwk** [comment]
了解しました．
リンク先は，dockerのイメージをビルドすることになっていますが，dlboxにcoral_usb_rosの環境を作るという認識であっていますでしょうか．

**Comment by knorth55** [comment]
dlboxでやる場合には、[ここ](https://github.com/knorth55/coral_usb_ros/tree/master/training/labelme_voc)のrun.bashだけ落としてくればできるはずです
```bash
cd ~
wget https://raw.githubusercontent.com/knorth55/coral_usb_ros/master/training/labelme_voc/run.sh
chmod +x run.bash
bash ./run.sh <your_dataset_path>
```

**Comment by shmpwk** [comment]
ありがとうございます．できました．
いろいろ知らないことが多いので，調べながら進めていきたいです．
